"""Some valid course names for the course_titles provider"""
course_titles = [
    "Computer Science",
    "Principles of Economics",
    "Modern Literature",
    "Organic Chemistry",
    "World History",
    "Calculus and Analytic Geometry",
    "Psychology",
    "Microbiology Fundamentals",
    "Principles of Marketing",
    "Environmental Science",
    "Sociology",
    "Financial Accounting",
    "Political Science and Government",
    "Human Anatomy",
    "Business Ethics",
    "Philosophy",
    "Statistics for Social Sciences",
    "Cell Biology",
    "Anthropology",
    "Principles of Management",
    "Macroeconomics",
    "General Physics",
    "English Composition",
    "Human Physiology",
    "Developmental Psychology",
    "Linguistics",
    "Genetics and Genomics",
    "Principles of Finance",
    "Art History",
    "Microeconomics",
    "Anatomy and Physiology",
    "Marketing",
    "Astronomy",
    "Political Science",
    "Microeconomics",
    "Business",
    "Cultural Anthropology",
    "American History",
    "World Religions",
    "Chemistry",
    "Environmental Science",
    "Communication",
    "General Chemistry",
    "Cultural Anthropology",
    "Human Biology",
    "Theatre",
    "Public Speaking",
    "International Relations",
    "Sociology",
    "Criminal Justice",
    "Statistics",
    "Human Anatomy",
    "Western Civilization",
    "Literature",
    "Biochemistry",
    "Physical Anthropology",
    "Human Physiology",
    "Creative Writing",
    "Film Studies",
    "Music",
    "Ethics",
    "Philosophy of Science",
    "Philosophy of Mind",
    "Philosophy of Language",
    "Political Philosophy",
    "Philosophy of Religion",
    "Epistemology",
    "Metaphysics",
    "Logic",
    "Symbolic Logic",
    "Modal Logic",
    "Mathematical Logic",
    "Computer Science",
    "Programming",
    "Algorithms",
    "Data Structures",
    "Software Engineering",
    "Computer Networks",
    "Operating Systems",
    "Database Systems",
    "Artificial Intelligence",
    "Machine Learning",
    "Computer Vision",
    "Natural Language Processing",
    "Robotics",
    "Human-Computer Interaction",
    "Virtual Reality",
    "Augmented Reality",
    "Web Development",
    "Mobile Development",
    "Development",
    "Cybersecurity",
    "Cryptography",
    "Digital Forensics",
    "Cloud Computing",
    "Big Data",
    "Data Science",
    "Data Analytics",
    "Data Visualization",
    "Business Intelligence",
    "Information Systems",
    "E-commerce",
    "Web Design",
    "User Experience Design",
    "User Interface Design",
    "Graphic Design",
    "Multimedia Design",
    "Animation",
    "Digital Art",
    "Photography",
    "Videography",
    "Audio Production",
    "Sound Design",
    "Music Production",
    "Film Production",
    "Screenwriting",
    "Directing",
    "Cinematography",
    "Film Editing",
    "Visual Effects",
    "Motion Graphics",
    "3D Modeling",
    "3D Animation",
    "Design",
    "Programming",
    "Art",
    "Sound",
    "Narrative",
    "Testing",
    "Marketing",
    "Publishing",
    "Monetization",
    "Analytics",
    "Localization",
    "Development Tools",
    "Engines",
    "AI",
    "Networking",
    "Servers",
    "Security",
    "Design Patterns",
    "Theory",
    "History",
    "Culture",
    "Studies",
    "Journalism",
    "Criticism",
    "Law",
    "Ethics",
    "Philosophy",
    "Psychology",
    "Sociology",
    "Anthropology",
    "Archaeology",
    "Economics",
    "Marketing",
    "Management",
    "Development Methodologies",
    "Production",
    "Design Documents",
    "Prototyping",
    "Testing",
    "Quality Assurance",
    "Localization",
    "Voice Acting",
    "Music Composition",
    "Sound Design",
    "Art Direction",
    "Animation",
    "Character Design",
    "Environment Design",
    "Level Design",
    "Storytelling",
    "Writing",
    "Dialogue",
    "Cutscenes",
    "Worldbuilding",
    "Concept Art",
    "Production Design",
    "User Interface Design",
    "User Experience Design",
    "Interaction Design",
    "Control Design",
    "Camera Design",
    "Interface Design",
    "HUD Design",
    "Menu Design",
    "Navigation Design",
    "Inventory Design",
    "Map Design",
    "Mini-map Design",
    "Tutorial Design",
    "Help System Design",
    "Accessibility Design",
    "Reward System Design",
    "Progression System Design",
    "Achievement System Design",
    "Leaderboard Design",
    "Social System Design",
    "Community System Design",
    "Feedback System Design",
    "Chat System Design",
    "Messaging System Design",
    "Notification System Design",
    "Ranking System Design",
    "Matchmaking System Design",
    "Voting System Design",
    "Auction System Design",
]
