version: '3'

x-common-keys-selab: &common-keys-selab
  networks:
    selab_network:
      name: selab_network
      driver: bridge
      ipam:
        config:
          - subnet: 192.168.90.0/24


  env_file:
    - ".env"

services:
  nginx:
    <<: *common-keys-selab
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    depends_on:
      - frontend
      - backend
    volumes:
       - ${DATA_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  frontend:
    <<: *common-keys-selab
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    <<: *common-keys-selab
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

