version: '3.9'

networks:
  selab_network:
    name: selab_network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24

x-common-keys-selab: &common-keys-selab
  networks:
    - selab_network

  env_file:
    - ".env"

services:
  #certbot:
  #image: certbot/certbot:latest
  #volumes:
  #   - ./certbot/www/:/var/www/certbot/:rw
  #   - ./certbot/conf/:/etc/letsencrypt/:rw
  nginx:
    <<: *common-keys-selab
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend
    volumes:
       - ${DATA_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
       - /etc/letsencrypt/:/etc/letsencrypt/:rw 
       - ./certbot/www:/var/www/certbot/:ro
         #- ./certbot/conf/:/etc/nginx/ssl/:ro
  frontend:
    <<: *common-keys-selab
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - backend
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:rw
  backend:
    <<: *common-keys-selab
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000

