version: '3'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

