FROM python:3.9

# Set the working directory
WORKDIR /app

# Copy the application code into the container
COPY . /app

# Install dependencies
RUN apt-get update 
RUN apt-get install -y --no-install-recommends python3-pip
RUN pip3 install -r requirements.txt -r dev-requirements.txt
