FROM docker:dind

RUN apk add --no-cache \
    python3 \
    py3-pip

WORKDIR /app

RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

COPY . /app

RUN pip3 install --no-cache-dir -r requirements.txt -r dev-requirements.txt
