name: UGent-3-frontend-linter
run-name: ${{ github.actor }} is running frontend linter 🚀
on: [pull_request]
jobs:
  Frontend-tests:
    if: contains(github.event.pull_request.changed_files.*.filename, 'frontend/')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
          
      - name: Install dependencies
        working-directory: ./frontend
        run: npm i eslint
      
      - name: Run linting
        working-directory: ./frontend
        run: npm run lint
        