name: UGent-3-frontend-test
run-name: ${{ github.actor }} is running frontend tests 🚀
on:
  pull_request:
    paths:
      - 'frontend/**'
jobs:
  Frontend-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
          
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
      
      - name: Build
        working-directory: ./frontend
        run: npm run build
      
      - name: Preview Web App
        working-directory: ./frontend
        run: npm run preview &

      - name: Running tests
        working-directory: ./frontend
        run: npm test

